## PostgreSQL connection
#quarkus.datasource.db-kind=postgresql
#quarkus.datasource.username=merchant
#quarkus.datasource.password=123456
#quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/merchant
#
## Hibernate settings
#quarkus.hibernate-orm.database.generation=update
#quarkus.hibernate-orm.log.sql=true
#
## MongoDB connection config
#quarkus.mongodb.connection-string=mongodb://localhost:27017
#quarkus.mongodb.database=merchant
quarkus.devservices.enabled=false
quarkus.container-image.build=false
quarkus.http.cors=true
quarkus.http.cors.origins=https://your-angular-app.com,http://localhost:4200
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type

quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
quarkus.datasource.username=sa
quarkus.datasource.password=

quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true

partner.auth-token=Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiIwMUo4UEpSNE5YQTlTMEdOUVI0WlFZN1NLQyIsImF1ZCI6IlRISVJEX1BBUlRZIiwidXNyIjoiUEFZT04iLCJyb2xlcyI6W10sInR5cGUiOiIzUkRfVE9LRU4iLCJpYXQiOjE3MjczMzQ3NjUsImV4cCI6MjM1ODQ3MzgwNSwianRpIjoiMDFKOFBKU04wNUdINjYyMDYzQjBONzc1TVQifQ.iGRygKFBoN7Y2G9suqlqrs21oCotCoD8KQIINKMfJ8DRrF5PT/IrejvicToeQcdzCrvPw7LVzIeHXY6K7e9KvNekYOE+I2GGrDNgmTxMHENsKu4+Fj1IidNlwM0hWwA4rmMMszyT1/H1l0IkasI62Da9FeWflPHYvg1Oc2O4bIhQjMOaAb8S/X/SxIj8Pc1XDhYzBlTleamPh32pBPzDzO2GlNCYRYoCaMoNDtYjAQ1JUBa+HidDKrGXvpbh/1AXUCvrjZIK33NXEXVimydVLVo70/6YY4qMXd4sZmqjF7EKzcqiBwPWAWShBRjT60MGEr6w9MTQOugH3RcTa8o2EZZiFl3hVBuLBActXvcEhkqmaurRh75nH+5K6nbUjDppmQp37UXhN5f/BNf49a9cuDgcBuK4SucYxiwJlvZHVKi9xa7izGDvBBnOYto69PZHdvnmZx2irjP1FRrJRiQjCESuLHSXvwhsXpDpoSjHncQLK5EWIXgEjwEZ0jdMmbJfLaBtwtzcK8w424IcpEj7Mc+JMdHGiTv0PbPyaMIQPMgMq5BEHvNghkQHVqFZBeGsndHZ2Tfj7qubR+royerg7+Vlf0Vop4OvyPYPY48pWl89EBCuk6eXA5DL64lrQo44S+lKBMPPdW9otI0iu4lSBWwsoKK+R3vfcVI1rpcazfY=
partner.return-url=https://google.com
partner.cancel-url=https://google.com